### ISSUE TITLE
Yellow Notices

### ISSUE THREAD

**Issue by epischel** [bundesAPI/interpol-api#1]
wenn man in der URL "red" durch "yellow" ersetzt, erhält man yellow notices. Lt. Wikipedia sind dies Ersuchen um "Hilfe bei der Ortung vermisster Personen, häufig Jugendlicher, oder Hilfe bei der Identifizierung von Personen, die sich nicht selbst identifizieren können. " Sicherlich genauso interessant wie die red notices.

**Comment by AndreasFischer1985** [comment]
In der Tat eine spannende Ergänzung -habe ich soeben nachgetragen.

**Comment by epischel** [comment]
Im Abschnitt zu yellow notices beginnt fälschlicherweise mit "Red Notice" (Zeile 10)

**Comment by AndreasFischer1985** [comment]
Besten Dank, das habe ich im Zuge der Ergänzung von "UN Notices" soeben mit erledigt (https://github.com/bundesAPI/interpol-api/pull/4).
